from setuptools import setup

setup(
    name="BrokerPython",
    version="0.1",
    py_modules=['main'],
    install_requires=[
        'Click',
        'grpcio',
        'grpcio-tools',
        'gym',
        'h5py',
        'keras',
        'keras-rl',
        'mypy',
        #'mypy-protbuf',
        'numpy',
        'pandas',
        'PyDispatcher',
        'protobuf',
        'scikit-learn',
        'beautifulsoup4',
        'lxml',
        #'tensorflow-gpu',
        ],
    extras_require = {
        'visualize':[
            'jupyter',
            'tensorboard'
            ],
        'tests':[
            'pytest',
            'pytest-watch'
            ]
        },
    entry_points='''
        [console_scripts]
        agent=main:cli
    ''')
